In [2]:
import os
import sys
import datetime
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

sys.path.insert(0, '../../retrosheet')
sys.path.insert(0, '../../pybaseball')

from retrosheet import Retrosheet # https://github.com/calestini/retrosheet
import pybaseball as pbb # https://github.com/jldbc/pybaseball
pbb.cache.enable()

import psycopg2
from sqlalchemy import create_engine

In [5]:
class Database:
    """"""
    def __init__(self):
        self.creds = {
            'database': 'baseball',
            'user': 'tjordan',
            'password': '',
            'host': '127.0.0.1',
            'port': '5432',
        }

        self.engine = create_engine('postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}'.format(**self.creds))
        self.conn = psycopg2.connect(**self.creds)
        self.conn.autocommit = True
        self.cursor = self.conn.cursor()

In [6]:
db = Database()

In [2]:
class RetroETL:
    def __init__(self):
        self.SEASON_RANGE = (2017,2017)
        self.GAME_LOOKBACK = [None,3,6,9,12,20,50]
        self.ATBAT_LOOKBACK = [None,20,50,100,300,600]
        
        self.rs = Retrosheet()
        self.retro_fpath = os.path.join(os.getcwd(),'retrosheet')
        self.retro_datasets = [
            'batting','fielding','info','lineup',
            'pitching','plays','rosters','running','teams',
        ]

        
    def setup(self,cursor):
        os.makedirs(self.retro_fpath)

        cursor.execute('''create schema base''')
        cursor.execute('''create schema proc''')
    
    def extract(self):
        try:
            os.chdir(self.retro_fpath)
            self.rs.batch_parse(
                yearFrom=self.SEASON_RANGE[0],
                yearTo=self.SEASON_RANGE[1],
                batchsize=10
            )
        except:
            raise
        finally:
            os.chdir(self.retro_fpath+'/..')
    
    def load(self):
        for dataset in self.retro_datasets:
            setattr(self,f'DF_{dataset.upper()}',pd.read_csv(f'{self.retro_fpath}/{dataset}.csv'))

    def transform(self):
        None
    
    def write(self,engine):
        for table,data in self.retro_data.items():
            data.to_sql(
                table.replace('RS_','').lower(),engine,
                schema='base',#database='baseball',
                if_exists='replace',index=False,
            )

In [3]:
retro = RetroETL()
# retro.setup(db.cursor)
retro.extract()
retro.load()
retro.transform()
# retro.write(db.engine)

[============================================================] 100.0% ... Completed 2017-2017

In [4]:
retro.PLAYS

,game_id,order,pitcher,pitch_count,inning,team,player_id,count_on_batter,pitch_str,play_str,B,1,2,3,H,run,out,on-B,on-1,on-2,on-3,on-H,hometeam_score,awayteam_score,trajectory,passes,location,pre_state,post_state,play_runs,play_outs
0,ANA201704070,0,chavj001,6,1,0,seguj002,32,CBSBBB,W,0,1,0,0,0,0,0,NaN,seguj002,NaN,NaN,[],0,0,NaN,[],NaN,1,2,0,0
1,ANA201704070,1,chavj001,12,1,0,hanim001,12,1CB1FT,K,0,1,0,0,0,0,1,NaN,seguj002,NaN,NaN,[],0,0,NaN,[],NaN,2,10,0,1
2,ANA201704070,2,chavj001,15,1,0,canor001,11,BFX,8/F,0,1,0,0,0,0,2,NaN,seguj002,NaN,NaN,[],0,0,F,['8'],NaN,10,18,0,1
3,ANA201704070,3,chavj001,18,1,0,cruzn002,1,C1>S,SB2,0,0,1,0,0,0,2,cruzn002,NaN,seguj002,NaN,[],0,0,NaN,[],NaN,18,19,0,0
4,ANA201704070,4,chavj001,21,1,0,cruzn002,22,C1>S.*BBS,K,0,0,1,0,0,0,3,NaN,NaN,seguj002,NaN,[],0,0,NaN,[],NaN,19,25,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188901,WAS201709300,74,kintb001,22,9,0,morom001,0,X,T8/L.3-H;2-H;1-H,0,0,0,1,1,4,2,NaN,NaN,NaN,morom001,"['marts002', 'luplj001', 'rodrs002', 'diaze005']",1,0,L,['8'],NaN,24,20,3,0
188902,WAS201709300,77,solis001,5,9,0,bostc001,22,..BBCSX,7/F,0,0,0,1,1,4,3,NaN,NaN,NaN,morom001,"['marts002', 'luplj001', 'rodrs002', 'diaze005']",1,0,F,['7'],NaN,20,25,0,1
188903,WAS201709300,79,rivef001,2,9,1,difow001,1,.SX,8/F,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,[],1,4,F,['8'],NaN,1,9,0,1
188904,WAS201709300,80,rivef001,7,9,1,murpd006,12,BSSFS,K,0,0,0,0,0,0,2,NaN,NaN,NaN,NaN,[],1,4,NaN,[],NaN,9,17,0,1
188905,WAS201709300,81,rivef001,9,9,1,linda001,1,CX,8/F,0,0,0,0,0,0,3,NaN,NaN,NaN,NaN,[],1,4,F,['8'],NaN,17,25,0,1

In [ ]:
class PybballETL:
    """"""
    def __init__(self):
        None

    def extract_pbb(self):
        team_lkup = pbb.teamid_lookup.team_ids()[['yearID','teamID','teamIDBR','teamIDretro']]
        team_lkup = team_lkup.loc[
            (team_lkup.yearID>=self.season_range[0])
            & (team_lkup.yearID<=self.season_range[1])
        ]
        player_lkup = None
        
        data = []
        for year_team in team_lkup.values:
            try:
                data.append(
                    pbb.schedule_and_record(year_team[0],year_team[2])
                    .assign(SEASON=year_team[0])
                )
            except:
                # print(year_team)
                # raise
                pass

        self.pbb_data = {
            'SCHEDULE_RECORD': pd.concat(data).merge(
                team_lkup,how='inner',
                left_on=['Tm','SEASON'],
                right_on=['teamIDBR','yearID'],
            ),
        }

In [3]:
pbb.teamid_lookup.team_ids()[['yearID','teamID','teamIDBR','teamIDretro']].yearID.max()

2020

In [78]:
class ETL:
    def __init__(self):
        self.SEASON_RANGE = (2017,2017)
        self.GAME_LOOKBACK = [None,3,6,9,12,20,50]
        self.ATBAT_LOOKBACK = [None,20,50,100,300,600]

In [5]:
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,2B,3B,HR,R,RBI,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,GB,FB,LD,IFFB,Pitches,Balls,Strikes,IFH,BU,BUH,BB%,K%,BB/K,OBP,SLG,OPS,ISO,BABIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR,Dol,Spd,wRC+,WPA,-WPA,+WPA,RE24,REW,pLI,phLI,PH,WPA/LI,Clutch,FB% (Pitch),FBv,SL%,SLv,CT%,CTv,CB%,CBv,CH%,CHv,SF%,SFv,KN%,KNv,XX%,PO%,wFB,wSL,wCT,wCB,wCH,wSF,wKN,wFB/C,wSL/C,wCT/C,wCB/C,wCH/C,wSF/C,wKN/C,O-Swing%,Z-Swing%,Swing%,O-Contact%,Z-Contact%,Contact%,Zone%,F-Strike%,SwStr%,BsR,FA% (sc),FT% (sc),FC% (sc),FS% (sc),FO% (sc),SI% (sc),SL% (sc),CU% (sc),KC% (sc),EP% (sc),CH% (sc),SC% (sc),KN% (sc),UN% (sc),vFA (sc),vFT (sc),vFC (sc),vFS (sc),vFO (sc),vSI (sc),vSL (sc),vCU (sc),vKC (sc),vEP (sc),vCH (sc),vSC (sc),vKN (sc),FA-X (sc),FT-X (sc),FC-X (sc),FS-X (sc),FO-X (sc),SI-X (sc),SL-X (sc),CU-X (sc),KC-X (sc),EP-X (sc),CH-X (sc),SC-X (sc),KN-X (sc),FA-Z (sc),FT-Z (sc),FC-Z (sc),FS-Z (sc),FO-Z (sc),SI-Z (sc),SL-Z (sc),CU-Z (sc),KC-Z (sc),EP-Z (sc),CH-Z (sc),SC-Z (sc),KN-Z (sc),wFA (sc),wFT (sc),wFC (sc),wFS (sc),wFO (sc),wSI (sc),wSL (sc),wCU (sc),wKC (sc),wEP (sc),wCH (sc),wSC (sc),wKN (sc),wFA/C (sc),wFT/C (sc),wFC/C (sc),wFS/C (sc),wFO/C (sc),wSI/C (sc),wSL/C (sc),wCU/C (sc),wKC/C (sc),wEP/C (sc),wCH/C (sc),wSC/C (sc),wKN/C (sc),O-Swing% (sc),Z-Swing% (sc),Swing% (sc),O-Contact% (sc),Z-Contact% (sc),Contact% (sc),Zone% (sc),Pace,Def,wSB,UBR,Age Rng,Off,Lg,wGDP,Pull%,Cent%,Oppo%,Soft%,Med%,Hard%,TTO%,CH% (pi),CS% (pi),CU% (pi),FA% (pi),FC% (pi),FS% (pi),KN% (pi),SB% (pi),SI% (pi),SL% (pi),XX% (pi),vCH (pi),vCS (pi),vCU (pi),vFA (pi),vFC (pi),vFS (pi),vKN (pi),vSB (pi),vSI (pi),vSL (pi),vXX (pi),CH-X (pi),CS-X (pi),CU-X (pi),FA-X (pi),FC-X (pi),FS-X (pi),KN-X (pi),SB-X (pi),SI-X (pi),SL-X (pi),XX-X (pi),CH-Z (pi),CS-Z (pi),CU-Z (pi),FA-Z (pi),FC-Z (pi),FS-Z (pi),KN-Z (pi),SB-Z (pi),SI-Z (pi),SL-Z (pi),XX-Z (pi),wCH (pi),wCS (pi),wCU (pi),wFA (pi),wFC (pi),wFS (pi),wKN (pi),wSB (pi),wSI (pi),wSL (pi),wXX (pi),wCH/C (pi),wCS/C (pi),wCU/C (pi),wFA/C (pi),wFC/C (pi),wFS/C (pi),wKN/C (pi),wSB/C (pi),wSI/C (pi),wSL/C (pi),wXX/C (pi),O-Swing% (pi),Z-Swing% (pi),Swing% (pi),O-Contact% (pi),Z-Contact% (pi),Contact% (pi),Zone% (pi),Pace (pi),FRM,AVG+,BB%+,K%+,OBP+,SLG+,ISO+,BABIP+,LD+%,GB%+,FB%+,HR/FB%+,Pull%+,Cent%+,Oppo%+,Soft%+,Med%+,Hard%+,EV,LA,Barrels,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
1,18401,2023,Ronald Acuna Jr.,ATL,25,84,337,385,113,67,24,1,21,77,54,42,2,48,4,2,0,7,40,7,0.335,145,90,56,6,1483,598,885,16,0,0,0.109,0.125,0.88,0.413,0.599,1.012,0.264,0.341,0.0161,0.192,0.498,0.309,0.067,0.233,0.110,0.0,0.428,35.0,82,33.2,-0.1,11.9,-3.8,47.6,4.8,$38.1,6.9,170,3.60,-5.15,8.75,41.51,4.28,0.91,NaN,0,3.55,0.42,0.501,93.7,0.233,85.0,0.064,89.3,0.078,80.0,0.096,85.4,0.028,85.0,NaN,NaN,0.008,NaN,17.5,11.2,1.0,5.8,-1.0,2.4,NaN,2.37,3.27,1.08,5.02,-0.67,5.74,NaN,0.271,0.719,0.456,0.736,0.868,0.822,0.414,0.587,0.081,5.3,0.301,NaN,0.062,0.024,0.002,0.194,0.234,0.059,0.020,0.003,0.098,0.001,NaN,NaN,94.0,NaN,89.4,84.7,81.4,94.1,85.0,79.1,81.8,54.2,85.6,81.3,NaN,-2.3,NaN,0.5,-4.9,-6.1,-7.0,1.9,1.8,3.1,-3.9,-1.4,-7.0,NaN,9.1,NaN,4.9,1.8,-0.2,5.2,1.3,-5.5,-5.5,6.9,3.9,-2.6,NaN,13.0,NaN,0.5,1.9,0.0,4.0,9.3,5.3,0.1,0.4,-0.5,0.1,NaN,2.93,NaN,0.52,5.46,0.30,1.40,2.69,6.13,0.39,10.68,-0.35,4.27,NaN,0.235,0.676,0.457,0.669,0.873,0.821,0.504,18.1,-3.9,4.3,1.7,25 - 25,38.4,1.1,-0.7,0.457,0.333,0.210,0.100,0.460,0.440,0.288,0.099,NaN,0.078,0.293,0.060,0.027,NaN,0.001,0.201,0.240,NaN,85.4,NaN,79.6,94.1,89.7,84.8,NaN,81.9,94.4,85.3,NaN,-1.3,NaN,2.9,-1.9,0.8,-4.7,NaN,-6.6,-6.8,2.3,NaN,2.5,NaN,-7.2,8.2,4.0,0.5,NaN,-4.1,4.1,0.1,NaN,-0.4,NaN,3.6,13.0,1.2,2.0,NaN,0.1,3.9,9.9,NaN,-0.25,NaN,3.19,3.03,1.44,4.99,NaN,4.27,1.33,2.83,NaN,0.230,0.673,0.456,0.655,0.878,0.823,0.510,18.1,NaN,134,123,55,128,145,162,114,0.95,116,84,187,112,97,85,64,89,135,94.7,7.8,45,0.155,116.7,159,0.546,291,0.140,0.221,0.353,0.665,0.463,4.7
0,19755,2023,Shohei Ohtani,LAA,28,85,327,382,99,48,15,5,31,61,68,47,4,85,1,2,0,7,11,4,0.303,106,100,38,6,1513,595,918,7,0,0,0.123,0.223,0.55,0.390,0.664,1.054,0.361,0.319,0.0106,0.156,0.434,0.410,0.060,0.310,0.066,0.0,0.435,36.9,83,37.0,NaN,11.8,-9.2,41.3,4.1,$33.1,6.2,182,3.13,-6.05,9.18,37.99,3.97,1.03,NaN,0,3.89,-0.84,0.408,94.5,0.219,84.6,0.107,89.7,0.081,80.2,0.141,86.1,0.042,87.5,NaN,NaN,0.014,NaN,13.4,7.2,4.1,4.9,5.1,1.2,NaN,2.17,2.18,2.53,3.98,2.40,1.80,NaN,0.332,0.695,0.475,0.606,0.797,0.716,0.395,0.581,0.134,0.7,0.306,NaN,0.111,0.044,NaN,0.097,0.220,0.062,0.021,NaN,0.140,NaN,NaN,NaN,94.7,NaN,89.9,87.2,NaN,93.6,84.8,79.3,81.0,NaN,86.2,NaN,NaN,-2.0,NaN,0.3,-7.2,NaN,-1.1,0.8,3.6,2.9,NaN,-7.4,NaN,NaN,9.4,NaN,4.1,2.0,NaN,5.1,1.2,-5.5,-3.6,NaN,4.2,NaN,NaN,8.4,NaN,3.2,2.0,NaN,5.0,8.2,4.6,-0.1,NaN,4.3,NaN,NaN,1.81,NaN,1.91,2.96,NaN,3.39,2.46,4.95,-0.22,NaN,2.05,NaN,NaN,0.297,0.686,0.478,0.531,0.809,0.717,0.466,18.8,-9.2,-0.1,0.5,28 - 28,37.6,1.1,0.3,0.389,0.365,0.246,0.094,0.496,0.410,0.427,0.140,NaN,0.078,0.295,0.099,0.043,NaN,NaN,0.102,0.242,NaN,86.2,NaN,80.0,94.6,90.7,87.0,NaN,NaN,94.1,84.7,NaN,-7.3,NaN,3.3,-1.7,1.1,-6.7,NaN,NaN,-1.7,0.7,NaN,2.8,NaN,-6.8,8.5,3.9,0.7,NaN,NaN,4.1,-0.4,NaN,4.3,NaN,4.6,6.6,2.4,1.5,NaN,NaN,5.6,8.4,NaN,2.03,NaN,3.89,1.49,1.63,2.37,NaN,NaN,3.65,2.31,NaN,0.295,0.680,0.478,0.521,0.811,0.717,0.475,18.8,NaN,123,147,97,123,163,224,108,0.77,103,108,257,95,105,101,61,95,127,93.9,13.4,46,0.185,117.1,129,0.518,249,0.129,0.263,0.297,0.658,0.434,4.1
10,20043,2023,Luis Robert,CHW,25,83,315,349,87,41,22,0,24,59,46,20,3,100,9,0,0,6,8,2,0.276,82,92,41,11,1328,417,911,8,0,0,0.057,0.287,0.20,0.337,0.575,0.912,0.298,0.330,0.0089,0.191,0.381,0.428,0.120,0.261,0.098,0.0,0.383,18.7,61,19.3,4.7,10.8,1.2,37.5,3.8,$30.0,4.9,147,1.76,-6.18,7.94,14.83,1.43,1.02,1.53,1,2.39,-0.67,0.416,93.9,0.347,84.5,0.075,88.4,0.074,79.4,0.066,85.3,0.022,86.5,NaN,NaN,0.011,NaN,9.7,-0.8,4.5,2.1,2.1,0.0,NaN,1.77,-0.18,4.51,2.11,2.38,0.04,NaN,0.414,0.759,0.551,0.521,0.818,0.684,0.398,0.670,0.174,0.6,0.257,NaN,0.073,0.012,NaN,0.158,0.347,0.066,0.011,NaN,0.076,NaN,NaN,NaN,93.9,NaN,88.6,85.8,NaN,93.6,84.4,79.0,83.0,NaN,85.6,NaN,NaN,-2.4,NaN,0.7,-7.0,NaN,-6.9,2.9,-1.1,2.2,NaN,-1.1,NaN,NaN,9.6,NaN,4.0,3.4,NaN,4.9,1.1,-5.5,-3.9,NaN,3.4,NaN,NaN,17.3,NaN,3.8,0.3,NaN,-7.6,-1.0,2.8,0.1,NaN,1.8,NaN,NaN,5.08,NaN,3.89,1.63,NaN,-3.65,-0.21,3.19,0.83,NaN,1.83,NaN,NaN,0.368,0.748,0.555,0.435,0.816,0.688,0.492,18.8,5.9,0.3,-0.3,25 - 25,19.9,1.0,0.6,0.419,0.353,0.228,0.205,0.456,0.340,0.413,0.076,0.001,0.063,0.259,0.075,0.012,NaN,NaN,0.154,0.359,NaN,85.8,80.0,79.1,94.2,88.8,85.9,NaN,NaN,93.8,84.6,NaN,-0.8,4.2,-0.6,-2.1,1.2,-6.5,NaN,NaN,-6.8,3.4,NaN,2.1,-9.0,-7.7,8.6,2.9,1.9,NaN,NaN,3.8,-0.2,NaN,1.8,0.0,1.5,15.4,3.6,0.3,NaN,NaN,-7.6,0.3,NaN,1.83,0.00,1.80,4.49,3.62,1.63,NaN,NaN,-3.70,0.07,NaN,0.373,0.742,0.555,0.440,0.815,0.688,0.494,18.8,NaN,112,68,125,107,141,185,112,0.95,91,113,216,102,102,93,133,87,105,88.9,15.6,34,0.155,113.6,87,0.395,220,0.131,0.305,0.264,0.534,0.365,3.6
7,13611,2023,Mookie Betts,LAD,30,81,313,372,84,41,20,1,22,64,56,50,0,63,4,5,0,4,7,2,0.268,76,125,54,12,1433,599,834,5,0,0,0.134,0.169,0.79,0.371,0.550,0.920,0.281,0.266,0.0061,0.212,0.298,0.490,0.096,0.176,0.066,0.0,0.390,22.0,67,22.1,0.8,11.5,-1.7,36.5,3.7,$29.3,4.9,148,2.68,-5.60,8.29,28.15,2.85,0.97,1.14,1,2.59,0.17,0.530,93.9,0.232,84.7,0.081,88.3,0.071,79.9,0.068,86.3,0.017,89.1,NaN,NaN,0.003,NaN,15.3,6.0,-0.5,2.5,1.7,-0.7,NaN,2.02,1.81,-0.41,2.48,1.77,-2.65,NaN,0.196,0.631,0.383,0.600,0.933,0.835,0.429,0.562,0.063,2.7,0.319,NaN,0.097,0.020,NaN,0.206,0.220,0.048,0.023,NaN,0.066,0.001,NaN,NaN,94.2,NaN,88.6,89.5,NaN,93.3,84.4,79.6,80.6,NaN,86.0,79.9,NaN,-2.4,NaN,0.5,-6.8,NaN,-4.5,2.6,0.9,3.6,NaN,-1.9,-6.2,NaN,9.2,NaN,4.2,2.5,NaN,5.0,1.3,-4.4,-4.6,NaN,3.5,-0.3,NaN,6.4,NaN,-1.1,0.5,NaN,9.3,7.3,-0.1,2.2,NaN,0.1,-0.2,NaN,1.40,NaN,-0.83,1.89,NaN,3.15,2.32,-0.13,6.62,NaN,0.11,-15.86,NaN,0.179,0.592,0.382,0.531,0.933,0.837,0.492,17.7,-0.9,-0.1,2.5,30 - 30,24.8,1.1,0.3,0.478,0.345,0.176,0.102,0.471,0.427,0.363,0.065,NaN,0.065,0.315,0.090,0.017,NaN,0.001,0.213,0.235,NaN,86.1,NaN,79.9,94.3,88.8,88.2,NaN,80.1,93.4,84.7,NaN,-1.6,NaN,2.7,-2.0,0.8,-6.1,NaN,-5.3,-4.3,3.2,NaN,2.3,NaN,-6.4,8.3,3.5,1.1,NaN,-2.3,3.9,0.1,NaN,-0.2,NaN,2.3,6.2,-1.2,0.3,NaN,-0.2,10.4,7.0,NaN,-0.24,NaN,2.46,1.38,-0.98,1.30,NaN,-15.86,3.45,2.10,NaN,0.175,0.591,0.381,0.544,0.928,0.839,0.497,17.7,NaN,107,152,75,115,133,173,89,1.05,70,133,141,117,100,71,66,91,132,92.4,19.5,31,0.122,110.1,123,0.482,255,0.200,0.262,0.280,0.553,0.400,3.6
62,23667,2023,Wander Franco,TBR,22,80,318,353,90,56,21,4,9,46,42,29,2,45,2,4,0,11,26,8,0.283,132,77,68,8,1360,510,850,7,0,0,0.082,0.127,0.64,0.343,0.459,0.802,0.176,0.302,0.0171,0.245,0.477,0.278,0.104,0.117,0.053,0.0,0.344,7.4,50,10.4,9.3,10.9,3.4,36.6,3.7,$29.3,7.1,125,0.87,-5.04,5.91,14.31,1.60,0.86,1.46,2,1.35,-0.34,0.409,93.7,0.176,84.2,0.094,89.3,0.092,80.5,0.202,85.8,0.027,87.1,NaN,NaN,0.007,NaN,11.9,5.0,-1.4,-2.7,-1.1,-2.0,NaN,2.13,2.08,-1.10,-2.16,-0.41,-5.39,NaN,0.289,0.636,0.441,0.805,0.918,0.876,0.439,0.629,0.054,1.6,0.292,NaN,0.092,0.021,0.004,0.115,0.175,0.079,0.018,NaN,0.204,NaN,NaN,NaN,94.0,NaN,89.0,86.8,85.2,93.4,84.1,79.9,83.6,NaN,85.8,NaN,NaN,-2.5,NaN,0.6,-7.4,-6.5,-5.3,2.5,2.3,2.1,NaN,-6.3,NaN,NaN,9.7,NaN,5.1,2.5,1.5,5.0,1.0,-5.2,-5.5,NaN,3.7,NaN,NaN,10.0,NaN,-0.1,-1.7,-0.1,2.1,1.8,-0.3,-0.9,NaN,-1.6,NaN,NaN,2.51,NaN,-0.10,-5.69,-2.12,1.32,0.75,-0.24,-3.77,NaN,-0.57,NaN,NaN,0.252,0.608,0.440,0.753,0.920,0.875,0.528,18.7,12.7,1.2,0.7,22 - 22,12.0,1.0,-0.3,0.419,0.350,0.231,0.141,0.513,0.347,0.235,0.207,NaN,0.082,0.295,0.092,0.022,NaN,NaN,0.111,0.191,NaN,86.1,NaN,80.7,94.0,89.5,86.7,NaN,NaN,93.6,84.5,NaN,-6.0,NaN,3.1,-2.4,1.1,-6.9,NaN,NaN,-5.1,2.8,NaN,2.2,NaN,-7.8,8.6,4.1,1.4,NaN,NaN,3.7,-0.5,NaN,-2.3,NaN,-1.9,9.4,-0.4,-1.2,NaN,NaN,2.0,3.3,NaN,-0.80,NaN,-1.71,2.35,-0.32,-3.84,NaN,NaN,1.35,1.26,NaN,0.254,0.605,0.440,0.765,0.915,0.875,0.531,18.7,NaN,115,98,56,108,113,109,103,1.22,113,73,97,102,101,95,92,98,108,88.5,8.6,17,0.061,111.0,105,0.379,277,0.183,0.238,0.292,0.450,0.349,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,15679,2023,Rowdy Tellez,MIL,28,78,253,283,54,34,7,1,12,23,35,27,2,66,0,3,0,9,0,0,0.213,68,86,36,9,1216,462,754,2,0,0,0.095,0.233,0.41,0.286,0.391,0.678,0.178,0.236,0.0079,0.189,0.358,0.453,0.105,0.140,0.029,0.0,0.292,-6.1,28,-6.7,-2.0,8.8,-5.4,-8.1,-0.8,($6.5),1.3,81,-0.83,-4.92,4.09,-4.86,-0.46,0.91,1.60,10,-0.37,-0.55,0.451,93.5,0.164,84.1,0.072,89.4,0.105,80.0,0.173,86.1,0.036,86.8,NaN,NaN,0.011,NaN,-8.4,-1.2,1.2,0.6,1.6,-0.6,NaN,-1.54,-0.60,1.38,0.47,0.75,-1.43,NaN,0.279,0.516,0.383,0.695,0.891,0.810,0.438,0.576,0.072,-3.5,0.281,NaN,0.077,0.039,0.002,0.167,0.162,0.087,0.020,NaN,0.166,NaN,NaN,NaN,93.7,NaN,89.7,87.2,82.2,93.1,84.0,79.7,81.6,NaN,85.9,NaN,NaN,-3.4,NaN,0.2,-7.0,-5.2,-4.8,1.0,4.2,4.1,NaN,-7.4,NaN,NaN,8.9,NaN,5.3,2.8,1.8,4.9,1.2,-6.2,-5.9,NaN,3.7,NaN,NaN,-0.8,NaN,1.9,-0.5,-0.2,-7.9,-1.0,0.6,-0.7,NaN,1.6,NaN,NaN,-0.24,NaN,2.04,-1.13,-6.80,-3.89,-0.52,0.59,-3.09,NaN,0.82,NaN,NaN,0.252,0.502,0.383,0.644,0.887,0.810,0.522,18.8,-7.4,-0.4,-1.8,28 - 28,-10.2,0.8,-1.3,0.384,0.395,0.221,0.189,0.495,0.316,0.371,0.168,NaN,0.102,0.268,0.081,0.038,NaN,NaN,0.174,0.168,NaN,86.1,NaN,80.0,93.9,90.3,86.4,NaN,NaN,93.2,84.1,NaN,-6.9,NaN,4.8,-2.9,0.7,-6.3,NaN,NaN,-4.7,1.4,NaN,2.2,NaN,-7.9,8.0,4.5,1.0,NaN,NaN,3.7,-0.1,NaN,1.5,NaN,0.6,0.0,1.0,-0.5,NaN,NaN,-8.3,-1.2,NaN,0.74,NaN,0.46,-0.01,1.07,-1.14,NaN,NaN,-3.94,-0.61,NaN,0.249,0.502,0.383,0.634,0.888,0.810,0.530,18.8,NaN,85,108,104,88,95,109,79,0.94,83,123,112,94,114,89,122,95,97,89.0,15.9,16,0.084,114.8,71,0.374,190,0.237,0.309,0.233,0.379,0.302,-0.7
141,19610,2023,Keibert Ruiz,WSN,24,69,266,288,61,42,10,0,9,23,31,16,0,23,5,1,0,11,0,0,0.229,95,95,54,13,932,315,617,3,0,0,0.056,0.080,0.70,0.285,0.368,0.653,0.139,0.221,0.0100,0.221,0.389,0.389,0.137,0.095,0.032,0.0,0.287,-7.4,27,-8.4,-11.6,8.9,4.8,-8.1,-0.8,($6.5),0.8,76,-1.05,-5.90,4.85,-7.01,-0.70,1.05,1.83,1,-0.87,-0.14,0.418,93.9,0.207,84.0,0.064,89.6,0.144,80.3,0.135,85.5,0.030,86.6,0.003,80.3,0.003,NaN,-3.1,2.5,-1.2,-3.2,-2.4,-1.8,-0.2,-0.80,1.29,-2.05,-2.38,-1.94,-6.42,-5.91,0.369,0.714,0.517,0.791,0.947,0.883,0.428,0.594,0.060,-2.7,0.286,NaN,0.065,0.023,0.004,0.130,0.206,0.122,0.031,NaN,0.130,NaN,0.003,NaN,94.2,NaN,89.3,87.3,81.7,93.2,84.0,79.9,81.1,NaN,86.2,NaN,79.9,-1.9,NaN,0.1,-6.8,-5.1,-1.1,0.8,2.9,3.5,NaN,-3.6,NaN,-6.0,9.0,NaN,5.1,3.0,1.0,5.2,0.9,-5.9,-4.7,NaN,2.8,NaN,-2.8,-0.1,NaN,-0.5,-2.2,0.0,-3.2,1.3,-0.9,-2.2,NaN,-2.1,NaN,-0.2,-0.04,NaN,-0.80,-10.51,-0.56,-2.62,0.70,-0.83,-7.73,NaN,-1.75,NaN,-5.91,0.351,0.686,0.517,0.758,0.949,0.883,0.494,18.7,-6.8,-0.5,-1.1,24 - 24,-11.1,0.9,-1.1,0.406,0.373,0.221,0.172,0.512,0.316,0.167,0.141,NaN,0.144,0.279,0.058,0.022,0.003,NaN,0.138,0.215,NaN,85.8,NaN,80.5,94.2,90.2,85.9,79.9,NaN,93.7,84.3,NaN,-3.3,NaN,3.7,-1.5,0.4,-5.6,-5.1,NaN,-1.6,0.9,NaN,1.4,NaN,-7.2,8.2,4.8,1.4,-3.9,NaN,4.2,-0.2,NaN,-3.3,NaN,-3.1,0.0,-0.9,-1.1,-0.2,NaN,-2.8,1.2,NaN,-2.52,NaN,-2.30,0.01,-1.63,-5.60,-5.91,NaN,-2.17,0.58,NaN,0.353,0.686,0.517,0.772,0.942,0.883,0.491,18.7,-9.6,91,63,35,88,89,86,74,1.09,91,106,76,100,108,89,111,99,97,88.8,14.8,20,0.082,109.2,90,0.369,244,0.145,0.205,0.287,0.475,0.351,-0.8
146,22197,2023,MJ Melendez,KCR,24,78,284,323,59,37,14,2,6,33,31,34,0,96,2,3,0,3,4,2,0.208,66,89,36,5,1309,473,836,5,0,0,0.105,0.297,0.35,0.294,0.335,0.629,0.127,0.286,0.0074,0.188,0.346,0.466,0.056,0.067,0.076,0.0,0.281,-10.0,29,-10.4,-4.2,10.0,-2.6,-7.9,-0.8,($6.4),4.7,73,-0.29,-5.90,5.61,-3.58,-0.36,1.04,3.30,2,-0.64,0.37,0.496,94.1,0.189,84.2,0.069,89.5,0.108,80.5,0.103,86.4,0.036,84.9,NaN,NaN,NaN,NaN,-6.7,-4.4,0.5,-0.2,1.7,1.4,NaN,-1.03,-1.76,0.57,-0.14,1.24,3.01,NaN,0.316,0.700,0.476,0.531,0.749,0.665,0.417,0.647,0.160,-1.6,0.374,NaN,0.073,0.040,NaN,0.118,0.190,0.086,0.021,NaN,0.099,NaN,NaN,NaN,94.3,NaN,90.2,85.7,NaN,93.1,84.1,79.7,83.5,NaN,86.1,NaN,NaN,-2.3,NaN,0.7,-6.7,NaN,-1.6,0.6,3.9,3.3,NaN,-7.2,NaN,NaN,9.0,NaN,5.0,2.5,NaN,5.0,1.0,-5.7,-5.3,NaN,4.2,NaN,NaN,-8.2,NaN,1.0,1.0,NaN,0.9,-5.2,-0.2,0.3,NaN,2.1,NaN,NaN,-1.68,NaN,1.05,1.97,NaN,0.56,-2.10,-0.22,1.23,NaN,1.60,NaN,NaN,0.283,0.661,0.476,0.481,0.740,0.665,0.511,17.8,-6.8,-0.6,-1.6,24 - 24,-12.0,0.9,0.6,0.445,0.314,0.241,0.084,0.518,0.398,0.421,0.096,NaN,0.101,0.371,0.073,0.042,NaN,NaN,0.120,0.197,NaN,86.3,NaN,80.5,94.5,90.1,85.8,NaN,NaN,93.3,84.4,NaN,-7.1,NaN,4.4,-2.3,1.0,-6.3,NaN,NaN,-1.3,0.5,NaN,3.0,NaN,-7.2,8.1,4.1,1.2,NaN,NaN,4.0,-0.3,NaN,2.1,NaN,0.6,-7.9,0.6,1.1,NaN,NaN,0.3,-5.3,NaN,1.66,NaN,0.48,-1.62,0.63,1.96,NaN,NaN,0.21,-2.04,NaN,0.285,0.661,0.476,0.492,0.736,0.665,0.509,17.8,-0.1,84,125,130,93,82,79,97,0.94,82,123,56,109,91,99,54,99,124,93.1,17.8,22,0.115,113.2,97,0.508,191,0.162,0.322,0.224,0.407,0.315,-0.6
104,10815,2023,Jurickson Profar,COL,30,75,294,337,72,45,19,2,6,36,31,35,0,62,3,4,0,8,1,0,0.245,94,83,59,13,1382,517,865,2,0,0,0.104,0.184,0.56,0.327,0.384,0.712,0.139,0.287,0.0113,0.250,0.398,0.352,0.157,0.072,0.021,0.0,0.314,-1.2,40,-7.9,-8.1,10.4,-3.6,-9.6,-1.0,($7.7),3.6,81,-0.24,-5.36,5.12,-7.49,-0.72,0.91,1.46,1,-0.68,0.41,0.478,93.8,0.195,84.8,0.102,89.8,0.075,80.3,0.131,86.1,0.019,86.2,NaN,NaN,0.003,NaN,4.6,-1.7,-3.1,1.1,-2.2,-0.4,NaN,0.69,-0.65,-2.22,1.03,-1.20,-1.44,NaN,0.283,0.725,0.478,0.661,0.900,0.821,0.440,0.617,0.085,-1.4,0.390,NaN,0.101,0.018,0.005,0.086,0.197,0.063,0.016,NaN,0.125,NaN,NaN,NaN,93.7,NaN,90.1,87.6,84.2,93.4,85.0,79.7,81.3,NaN,86.0,NaN,NaN,-2.0,NaN,0.1,-5.1,-3.7,-3.0,1.4,1.7,4.1,NaN,-3.2,NaN,NaN,8.2,NaN,4.4,2.1,1.2,5.2,1.1,-4.5,-5.6,NaN,3.1,NaN,NaN,2.2,NaN,-2.7,-0.1,-0.2,2.2,-4.4,-0.2,1.9,NaN,-2.2,NaN,NaN,0.41,NaN,-1.93,-0.22,-2.73,1.85,-1.63,-0.18,8.54,NaN,-1.26,NaN,NaN,0.245,0.689,0.478,0.606,0.890,0.821,0.525,18.1,-11.7,-0.4,0.2,30 - 30,-9.3,1.0,-1.2,0.483,0.322,0.195,0.199,0.449,0.352,0.306,0.124,0.001,0.073,0.383,0.107,0.027,NaN,NaN,0.091,0.194,NaN,86.1,77.3,80.4,94.1,90.3,87.2,NaN,NaN,93.4,85.0,NaN,-3.3,4.8,2.6,-1.8,0.0,-4.6,NaN,NaN,-3.4,1.6,NaN,2.1,-8.2,-5.9,7.7,3.7,1.6,NaN,NaN,4.0,0.2,NaN,-3.3,-0.2,1.4,1.5,-3.6,0.7,NaN,NaN,2.9,-3.3,NaN,-1.92,-10.61,1.39,0.29,-2.47,1.89,NaN,NaN,2.32,-1.24,NaN,0.250,0.691,0.478,0.627,0.886,0.821,0.517,18.1,NaN,98,117,82,101,93,86,96,1.23,93,95,58,118,93,79,128,86,108,86.5,13.0,11,0.046,108.0,76,0.321,237,0.146,0.232,0.255,0.361,0.319,-0.5
149,10472,2023,Enrique Hernandez,BOS,31,75,267,291,60,43,11,0,6,34,29,20,0,61,2,2,0,10,3,1,0.225,80,92,36,12,1126,414,712,3,0,0,0.069,0.210,0.33,0.282,0.333,0.615,0.109,0.267,0.0087,0.173,0.385,0.442,0.130,0.065,0.038,0.0,0.273,-10.9,24,-12.2,-9.3,9.0,2.7,-11.1,-1.1,($8.9),3.7,65,-1.61,-5.51,3.91,-19.49,-2.00,0.98,1.91,1,-1.44,-0.19,0.439,92.8,0.252,84.8,0.095,87.8,0.077,81.2,0.113,83.8,0.024,86.8,NaN,NaN,0.002,NaN,-5.8,-3.7,-2.1,0.9,-2.4,-1.4,NaN,-1.18,-1.30,-1.97,0.98,-1.92,-5.18,NaN,0.289,0.675,0.449,0.574,0.860,0.752,0.415,0.601,0.111,-2.1,0.292,NaN,0.108,0.017,NaN,0.135,0.241,0.073,0.007,0.008,0.119,NaN,NaN,NaN,93.7,NaN,87.9,86.0,NaN,93.4,84.6,81.0,83.1,45.5,84.0,NaN,NaN,-1.9,NaN,0.9,-8.4,NaN,-5.3,2.7,2.1,7.1,2.5,1.6,NaN,NaN,9.9,NaN,4.5,2.2,NaN,5.0,1.3,-4.0,-4.8,8.1,3.8,NaN,NaN,0.9,NaN,-0.6,-0.6,NaN,-5.4,-5.7,0.4,0.1,-1.0,-3.5,NaN,NaN,0.28,NaN,-0.54,-3.19,NaN,-3.56,-2.10,0.55,0.82,-11.59,-2.62,NaN,NaN,0.271,0.627,0.449,0.507,0.861,0.754,0.501,18.3,-6.7,-0.3,-0.3,31 - 31,-14.3,0.8,-1.5,0.385,0.346,0.269,0.192,0.558,0.250,0.299,0.129,NaN,0.067,0.291,0.103,0.017,NaN,NaN,0.132,0.261,0.001,81.8,NaN,81.4,94.1,88.5,86.2,NaN,NaN,93.7,84.8,85.1,1.5,NaN,3.1,-1.7,1.1,-7.6,NaN,NaN,-4.8,3.1,0.0,2.6,NaN,-6.2,8.8,3.6,0.8,NaN,NaN,3.7,-0.2,0.0,-4.8,NaN,1.3,1.0,-1.0,-0.6,NaN,NaN,-5.0,-6.1,-0.3,-3.32,NaN,1.78,0.30,-0.86,-3.19,NaN,NaN,-3.35,-2.09,-25.6,0.256,0.645,0.449,0.510,0.850,0.752,0.496,18.3,NaN,91,82,92,89,82,67,91,0.86,91,117,54,94,100,110,125,106,78,87.6,17.0,8,0.038,108.8,68,0.327,208,0.184,0.295,0.204,0.305,0.255,-0.7

In [4]:
batting = pbb.batting_stats(2023)

In [ ]:
batting.sort_values(['Name','Season']).groupby(['Season']).count()

In [ ]:
etl.player

In [ ]:
# etl.pbb_data['SCHEDULE_RECORD'].head(20)

In [670]:
pd.DataFrame([[1,2],[3,4]]).to_dict(orient='index')

{0: {0: 1, 1: 2}, 1: {0: 3, 1: 4}}

In [ ]:
etl.extract_pbb()

In [ ]:
# pbb.teamid_lookup.team_ids().loc[pbb.teamid_lookup.team_ids().teamID=='MIA']

In [ ]:
# pbb.schedule_and_record(2021,'MIA')

In [ ]:
etl.team.loc[etl.team.TEAM_ID=='SEA'].sort_values(['TEAM_ID','SEASON','DATE']).head(20)

In [ ]:
etl.rs_batting.stat.unique()

In [ ]:
etl.game

In [ ]:
etl.game

In [ ]:
etl.rs_lineup

In [ ]:
data = pbb.statcast(start_dt='2017-06-24', end_dt='2017-06-27')
# data = pbb.schedule_and_record(1927, 'NYY')
data.head()

In [ ]:
pbb.playerid_lookup('judge', 'aaron')

In [ ]:
df = pbb.schedule_and_record(2021,'WSN')

In [ ]:
mo_map = {
    'JAN': 1,'FEB': 2,'MAR': 3,'APR': 4,
    'MAY': 5,'JUN': 6,'JUL': 7,'AUG': 8,
    'SEP': 9,'OCT': 10,'NOV': 11,'DEC': 12,
}
df['DATE'] = df.Date.map(
    lambda x: datetime.date(
        2021,
        mo_map[x.split(',')[1].split(' ')[1].strip().upper()],
        int(x.split(',')[1].split(' ')[2].strip()),
    )
)

In [ ]:
df.head(20)